### ISSUE TITLE
Error when measure = "sparcc"

### ISSUE THREAD

**Issue by liangzhengjiao** [stefpeschel/NetCoMi#10]
> library('NetCoMi')
> data("amgut1.filt")
> measures <- c("pearson", "spearman", "bicor", "sparcc", "cclasso", "ccrepe",
               "propr","gcoda", "spieceasi", "spring" )
> testnet <- netConstruct(amgut1.filt,
                         filtTax = "highestVar",
                         filtTaxPar = list(highestVar = 20),
                         filtSamp = "totalReads",
                         filtSampPar = list(totalReads = 1000),
                         zeroMethod = "none", normMethod = "none",
                         measure = measures[4],
                         sparsMethod = "threshold", thresh = 0.3,
                         seed = 20190101)
Data filtering ...
0 samples removed.
107 taxa removed.
20 taxa and 289 samples remaining.
Calculate 'sparcc' associations ... Done.
Sparsify associations via 'threshold' ... Done.
> testprops <- netAnalyze(testnet, clustMethod = "cluster_fast_greedy",hubPar = "eigenvector")
Warning message:
In max(eigen_unnorm) : no non-missing arguments to max; returning -Inf
> summary(testprops)
Error in array(x, c(length(x), 1L), if (!is.null(names(x))) list(names(x),  : 
  'data' must be of a vector type, was 'NULL'

**Comment by stefpeschel** [comment]
The recent release should solve this issue. 

Stefanie
