### ISSUE TITLE
Calculating the Withing module degree (Z) and participation coefficient (P) values

### ISSUE THREAD

**Issue by drbmanna** [stefpeschel/NetCoMi#102]
Hi, 

Is there a direct way of calculating the Within module degree (Z) and participation coefficient (P) for each node from the NetCoMi pipeline as described here doi: 10.1088/1742-5468/2005/02/P02001 ?

Thank you.
BM

**Comment by stefpeschel** [comment]
Hi, 
No that's not implemented but sounds like meaningful properties.

**Comment by drbmanna** [comment]
Thank you. Please update in case it is implemented in the future.
