### ISSUE TITLE
Plotting with different line style

### ISSUE THREAD

**Issue by indrikwijaya** [stefpeschel/NetCoMi#103]
Hi @stefpeschel ,

Thanks for such a wonderful work for this package! I have a question whether the `plot` function allows for different line styles for the edges of the network. So, for example, any edges with correlation lower than 0.5 will be plotted as dashed lines, whereas any edges with correlation greater than 0.5 will be plotted as solid lines.

**Comment by stefpeschel** [comment]
Hi, 
Unfortunately, that's not possible. The qgraph() function, which NetCoMi uses for network plotting, has a `lty` argument, which you can also use in NetCoMi's plot function. However, the option to change the line type depending on the correlation is not implemented. Currently, edges with a weight below a threshold (defined via the `cut` parameter) can only be handled differently in terms of edge width and transparency.

**Comment by indrikwijaya** [comment]
Hi Stefanie, 

Thank you for your reply!
