### ISSUE TITLE
output format for Gephi visualization

### ISSUE THREAD

**Issue by ladywaspzhu** [stefpeschel/NetCoMi#106]
Hi Stephanie,

Thanks for your great package; it is very useful to me and easy to understand and use. However, i want to know whether i can get the Gephi format output so i can put it in Gephi, or if there is no direct format, which output i can use to make my own gephi-like format file?

Thanks again

Jiachen

**Comment by stefpeschel** [comment]
Hi Jiachen,
A little late, but hopefully still useful.... I added an example of how to export the network to Gephi to the readme.

**Comment by ladywaspzhu** [comment]
Hi Stephanie,
Thank you so much. That is very helpful.
