### ISSUE TITLE
Colored by phylum

### ISSUE THREAD

**Issue by estebannieto93** [stefpeschel/NetCoMi#107]
Hello,

I am trying to color the nodes by phylum as in the tutorial. But when I tried to do it the following error appeared

all(colnames(adja1) %in% names(featVecCol)) is not TRUE

but then I run separatly this comand : all(colnames(net_cclasso_genus$adja1) %in% names(phyla)) and the result was TRUE.

Do you know how to solve this problem?

**Comment by stefpeschel** [comment]
Hey, 
Does the error also occur if you run the tutorial or only with your data set?
Please make sure that your count matrix has row and column names, and that the names of the phyla vector matches the taxa names. If this is the case, could you please send me a small reproducible example via email? Can be a really small subset of your data or any other data that causes the error. And of course the code you used for generating the network. 
This would be helpful to solve the issue. 
Thanks!

**Comment by estebannieto93** [comment]
I could solve it. It was an error in the matrix.

Thanks!
