### ISSUE TITLE
stability values using spieceasi

### ISSUE THREAD

**Issue by lixiaopi1985** [stefpeschel/NetCoMi#108]
Hi Stef,

Thank you for the package. I have a quick question.

One of the reviewers inquired about the stability values using the spieceasi algorithm. I wondered if these values were stored in the netConstruct outputs? 

The code involved:
```
 NetCoMi::netConstruct(data, 
                                   normMethod = "clr", 
                                   zeroMethod = "multRepl", 
                                   sparsMethod = "none", 
                                   filtTax = "highestFreq",
                                   filtTaxPar = list(highestFreq=150),
                                   measure = "spieceasi",
                                   measurePar = list(pulsar.params = list(rep.num=50), nlambda = 50, lambda.min.ratio=1e-2),
                                   # thresh = cor_thresh, 
                                   verbose = 3)
```

Best,
Xiaoping

**Comment by stefpeschel** [comment]
Hi,
Sorry for the late reply.
No, the SpiecEasi output is currently not stored and returned by netConstruct(). But I will consider including it into the output in a future version.
