### ISSUE TITLE
installation on R 

### ISSUE THREAD

**Issue by CarlaCristinaUranga** [stefpeschel/NetCoMi#11]
Hi I am not able to install NetCoMi in R studio version 4.0.2. I have tried installing from a local Zip file as well as after turning this into a .tar.gz file. Here is the read-out of the R installation command, is there any way you can help with this? Thank you in advance.

> system("R CMD build NetCoMi")
* checking for file ‘NetCoMi/DESCRIPTION’ ... OK
* preparing ‘NetCoMi’:
* checking DESCRIPTION meta-information ... OK
* installing the package to process help pages
      -----------------------------------
ERROR: dependencies ‘SpiecEasi’, ‘WGCNA’, ‘doSNOW’, ‘propr’, ‘qgraph’, ‘SPRING’, ‘LaplacesDemon’, ‘cccd’ are not available for package ‘NetCoMi’
* removing ‘/private/var/folders/_9/dvqyx4xcx3wwstdv74lh0xw00003ms/T/Rtmp54FxM5/Rinst16f8769578a36/NetCoMi’
      -----------------------------------
ERROR: package installation failed

I tried installing the dependencies but still am not able to:

> install.packages("~/Downloads/SpiecEasi_1.1.0.tar.gz", repos = NULL, type="source")
Installing package into ‘/Users/curanga/R/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘SpiecEasi’ ...
** using staged installation
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Users/curanga/R/library/Rcpp/include' -I'/Users/curanga/R/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c ADMM.cpp -o ADMM.o
ADMM.cpp:25:9: warning: unused variable 'n' [-Wunused-variable]
    int n = A.n_cols;
        ^
ADMM.cpp:36:9: warning: unused variable 'l' [-Wunused-variable]
    int l = k;
        ^
ADMM.cpp:38:9: warning: unused variable 'n' [-Wunused-variable]
    int n = A.n_cols;
        ^
3 warnings generated.
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Users/curanga/R/library/Rcpp/include' -I'/Users/curanga/R/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Users/curanga/R/library/Rcpp/include' -I'/Users/curanga/R/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c matops.cpp -o matops.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Users/curanga/R/library/Rcpp/include' -I'/Users/curanga/R/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c sqrtNewton.cpp -o sqrtNewton.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Users/curanga/R/library/Rcpp/include' -I'/Users/curanga/R/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c svthresh.cpp -o svthresh.o
svthresh.cpp:11:9: warning: unused variable 'n' [-Wunused-variable]
    int n = A.n_cols;
        ^
1 warning generated.
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o SpiecEasi.so ADMM.o RcppExports.o matops.o sqrtNewton.o svthresh.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [SpiecEasi.so] Error 1
ERROR: compilation failed for package ‘SpiecEasi’
* removing ‘/Users/curanga/R/library/SpiecEasi’
Warning in install.packages :
  installation of package ‘/Users/curanga/Downloads/SpiecEasi_1.1.0.tar.gz’ had non-zero exit status

**Comment by CarlaCristinaUranga** [comment]
Ok I managed to install the dependencies separately, and am now getting this NetCoMi installation error:

Error: Failed to install 'unknown package' from GitHub:
  HTTP error 403.
  API rate limit exceeded for 68.8.138.131. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

  Rate limit remaining: 0/60
  Rate limit reset at: 2020-12-31 23:22:16 UTC

  To increase your GitHub API rate limit
  - Use `usethis::browse_github_pat()` to create a Personal Access Token.
  - Use `usethis::edit_r_environ()` and add the token as `GITHUB_PAT`.

**Comment by CarlaCristinaUranga** [comment]
And installing from a local zip:

> system("R CMD build NetCoMi")
* checking for file ‘NetCoMi/DESCRIPTION’ ... OK
* preparing ‘NetCoMi’:
* checking DESCRIPTION meta-information ... OK
* installing the package to process help pages
      -----------------------------------
* installing *source* package ‘NetCoMi’ ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Warning: multiple methods tables found for ‘which’
Warning: multiple methods tables found for ‘which’
Error: .onLoad failed in loadNamespace() for 'GO.db', details:
  call: dbFileConnect(dbfile)
  error: DB file '' not found
Execution halted
ERROR: lazy loading failed for package ‘NetCoMi’
* removing ‘/private/var/folders/_9/dvqyx4xcx3wwstdv74lh0xw00003ms/T/Rtmpa8tGkX/Rinst45a30e6ec88/NetCoMi’
      -----------------------------------
ERROR: package installation failed

**Comment by CarlaCristinaUranga** [comment]
Ok forget about it whoever is out there. I was able to install after researching the problem. I guess I was just talking to myself LOL

**Comment by janelucas** [comment]
Hi Carla,

I am also having an issue installing this program. Can you share how you were able to fix it! 

Thanks!
Jane

**Comment by nicolereynolds1** [comment]
Yes, please share!  I have been having similar issues, and have not been able to find the solution.

Thank you!

**Comment by nicolereynolds1** [comment]
My error is 

fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [DESeq2.o] Error 1
ERROR: compilation failed for package ‘DESeq2’
* removing ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/DESeq2’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.0/Resources/library/DESeq2’
Error: Failed to install 'NetCoMi' from GitHub:
  Failed to install 'DESeq2' from Bioc:
  (converted from warning) installation of package ‘/var/folders/73/w593mcxn65n17_hrn2sv_sy80000gn/T//Rtmp5wSWGV/file35962ebc7364/DESeq2_1.30.0.tar.gz’ had non-zero exit status

**Comment by nicolereynolds1** [comment]
OK after much trial and error and searching, I achieved a successful installation.

First, I had to install GNU Fortran compiler (https://mac.r-project.org/tools/) and add it to my path 
export PATH=$PATH:/usr/local/gfortran/bin

When I tried installing NetCoMi again, that's when I got the DESeq2 error.  During the installation process I chose to update all dependent packages, so they all were updated before hitting that error.  So then I installed DESeq2 separately 

BiocManager::install("DESeq2")

That was successful, so then I tried NetCoMi again

devtools::install_github("stefpeschel/NetCoMi")

but skipped all the package updates, and the installation finally worked.

Now i will try actually running the package... hopefully it will go smoothly!

**Comment by CarlaCristinaUranga** [comment]
Honestly things started to work when I implemented this:

To increase your GitHub API rate limit

Use usethis::browse_github_pat() to create a Personal Access Token.
Use usethis::edit_r_environ() and add the token as GITHUB_PAT.

I had to add the token. Then, I updated my fortran package as well! It is then that I was able to install the package. However, I did install all dependencies separately that kept preventing the final installation.

Yay!

**Comment by janelucas** [comment]
Thanks for the responses! 

I was also able to get the package to install by installing the updated version of the package. I also found that skipping the dependencies updates was key. 

Have either of you been able to adjust your plot so that the nodes have taxonomic information instead of just the taxonomic OTU/ASV id?

-Jane

**Comment by CarlaCristinaUranga** [comment]
Not yet, but I really want to see how to do this. I integrated the phyloseq package, so there must be a way of doing this via phyloseq. If I figure it out I will post it here.

Carla

**Comment by nicolereynolds1** [comment]
So now when I try to run an analysis, R crashes with a fatal error that I don't know how to identify.  :'(

**Comment by CarlaCristinaUranga** [comment]
Ok so I upgraded to R 4.0.3 and re-installed, this time all went through nicely. However, the nodeShape choice for plotting is not functioning.

**Comment by stefpeschel** [comment]
The release I just published should solve the issues mentioned above. Please reopen this issue if there are still problems with installing NetCoMi.

Stefanie
