### ISSUE TITLE
Looking for guidance on MANs Inference with samples from different metagenomics/metatranscriptomics studies

### ISSUE THREAD

**Issue by sayalaruano** [stefpeschel/NetCoMi#117]
Hello,

I'm Sebastian, working on my MSc thesis, aiming to create a knowledge graph of the wastewater treatment microbiome. We're using Netcomi for constructing Microbial Association Networks (MANs) from MGnify database metagenomics and metatranscriptomics data. Specifically, we are using the CCLasso method. However, we are facing these challenges and have some questions:

- **Insufficient Samples**: Many MGnify studies lack enough samples for MANs inference, leading us to combine data from various studies. Is combining samples from different studies a viable strategy for MANs inference in this context?

- **Data Heterogeneity**: The data exhibits variability in sequencing technologies (e.g., Illumina Hiseq, Nextseq, Nanopore, etc), experiment types (metagenomics, assembly, or metatranscriptomics), sampling countries, and other variables. How best can we account for the data's heterogeneity in our analyses using Netcomi?

Your expertise and advice would be incredibly valuable. Thanks for your time and assistance.

Sebastian

**Comment by stefpeschel** [comment]
Hi Sebastian,

If you conduct network analysis using differnt sample sizes you have to be aware that the research question changes. So, you have to point out that you're analyzing the microbial associations accross different data sets. But in principle there is nothing against it.

Regarding heterogeneity: NetCoMi cannot directly take heterogeneity into account. However, one thing you could do is performing a regression analysis with the microbial count data as response and do the network construction and analysis on the residuals. 

Best, 
Stefanie

**Comment by sayalaruano** [comment]
Hello Stefanie, 

Thanks a lot for the quick response. We will consider the fact that we are obtaining associations across studies to analyze the results and avoid making conclusions at the study level. 

Also, your suggestion to handle data heterogeneity is great, we did not think about it. But, if we use the residuals to build the MANs, should we use the same normalization (fractions) and zero treatment (pseudoZO) methods we used for the abundance data?

Thanks again for your help.

Best,

Sebastian

**Comment by stefpeschel** [comment]
Sorry @sayalaruano, I completely forgot to answer. You should perform the normalization and zero replacement steps at the beginning of the workflow, so before the regression analysis. It is then no longer necessary for the network analysis.

**Comment by sayalaruano** [comment]
Hi @stefpeschel! Thanks a lot for your answer, and sorry for not getting back earlier. The code and summary of our project are available in this [link](https://github.com/Multiomics-Analytics-Group/MicW2Graph) if you are interested in keeping track of projects that use NetCoMi.

Thanks a lot for your work and help.
