### ISSUE TITLE
Comparing more than two groups of samples in NetCoMi

### ISSUE THREAD

**Issue by fredoowarren** [stefpeschel/NetCoMi#127]
Hi,

Thanks for the great package. I have a question- the option to generate two networks with the unified layout is really useful, but it is limited when comparing network structure accross multiple timepoints. Is there a way to generate multiple networks with a unified layout with the package? I have given an example fo my code for a network comapring two timepoint, g1 and g2, below.

net_p <- netConstruct(g1, g2, taxRank = "Genus",
                           filtTax = "highestVar",
                           filtTaxPar = list(highestVar = 300),
                           zeroMethod = "pseudo",
                           normMethod = "clr",
                           measure = "pearson",
                           verbose = 0, seed = 123456)

net1 <- netAnalyze(net_p, clustMethod = "cluster_fast_greedy")

nclust <- as.numeric(max(names(table(netprops1$clustering$clust1))))

col <- c(topo.colors(nclust), rainbow(6))

plot(net1, 
     sameLayout = TRUE,
     layoutGroup = "union",
     colorVec = col,
     borderCol = "gray40", 
     nodeSize = "degree", 
     cexNodes = 0.9, cexLabels = 0.6, labelScale = FALSE,
     nodeSizeSpread = 3, 
     edgeTranspLow = 80, 
     edgeTranspHigh = 50,
     groupNames = c("Baseline", "240 min"), 
     showTitle = TRUE, 
     cexTitle = 2.8,
     mar = c(1,1,3,1), 
     repulsion = 0.9, 
     labels = TRUE, 
     rmSingles = "inboth",
     nodeFilter = "clustMin", 
     nodeFilterPar = 10, 
     nodeTransp = 50, 
     hubTransp = 30)

Thanks!

Fred

**Comment by junhuili** [comment]
I have the same question. Fred, have you been able to find a solution? 

Thanks,
Junhui

**Comment by stefpeschel** [comment]
Hi,
You can store the output of the plot function and reuse the layout. Here's an example:

```
# Load data sets from American Gut Project
data("amgut2.filt.phy")

# Split data into two groups: with and without seasonal allergies
amgut_season_yes <- phyloseq::subset_samples(amgut2.filt.phy, 
                                             SEASONAL_ALLERGIES == "yes")
amgut_season_no <- phyloseq::subset_samples(amgut2.filt.phy, 
                                            SEASONAL_ALLERGIES == "no")

# Network construction
net1 <- netConstruct(data = amgut_season_yes,
                     measure = "pearson",
                     normMethod = "mclr",
                     sparsMethod = "thresh",
                     thresh = 0.5)

net2 <- netConstruct(data = amgut_season_no,
                     measure = "pearson",
                     normMethod = "mclr",
                     sparsMethod = "thresh",
                     thresh = 0.5)

# Network analysis
props1 <- netAnalyze(net1, clustMethod = "cluster_fast_greedy")
props2 <- netAnalyze(net2, clustMethod = "cluster_fast_greedy")

# Network plot for the first network
p <- plot(props1)

# Second network with the same layout
plot(props2, 
     layout = p$layout$layout1)
```

**Comment by fredoowarren** [comment]
Ahhh that's great- thank you so much for your help!
