### ISSUE TITLE
Question about plotting 2 data sets 

### ISSUE THREAD

**Issue by CarlaCristinaUranga** [stefpeschel/NetCoMi#13]
Hi,
First of all, I love NetCoMi, but I have some basic math questions about how it works. I am comparing a "control" dataset with two other datasets separately. Why are the control layouts different depending on the dataset I am comparing it to? I would like to know if it is possible to keep the same layout in the control network plots or if the control network will change according to the compared dataset. What is the mathematical basis of this?

Best wishes,

Carla

**Comment by stefpeschel** [comment]
Hey Carla, 

thanks for using NetCoMi! I am pleased that you like the package.

Regarding the layout:
Looking at only two data sets, you have several layout options. Let's assume, the control data set is passed to NetCoMi's "data" argument (group 1) and the case data set to "data2" (group 2). Then you have the following layout options:
- Different layouts (the layout is computed for each network separately): plot(props, sameLayout = FALSE, ... )
- Use the layout computed for group 1 for both networks: plot(props, sameLayout = TRUE, layoutGroup = 1, ... )
- Use a union of the two computed layouts in both groups: plot(props, sameLayout = TRUE, layoutGroup = "union", ... )

Note that the default layout "spring" leads to the same layout with repeated plotting while the layout differs from run to run for igraph's "layout_with_fr", which is also a force-directed layout. So, in the latter case, you must set a seed to get exactly the same node positions in each repetition.

Now to your case with two "case" data sets: In principle, you should get the same layout for the control group in both cases if and only if the control network is exactly the same. A possible problem is the filter step in netConstruct(). If different taxa are filtered in both cases, you result in different networks. Make sure the "jointPrepro" argument is set to FALSE to avoid the problem (the default value depends on whether data2 or a group vector is given). 

In case you still don't get the same layout, NetCoMi's plot function offers the option for storing the layout. In your case I would suggest to store the layout of your first case-control combination and reuse the layout for the second case. Please make sure, both case data sets contain the same taxa. Here's the code:

# Plot networks of the first comparison (control vs. case1)
p <- plot(props_case1, sameLayout = TRUE, layoutGroup = 1, ... )

# Store layout of the "control" network (the layouts are the same in this case)
lay1 <- p$layout$layout1

# Plot networks of the second comparison (control vs. case2)
plot(props_case2, layout = lay1, ... )

I hope that helps.

Please let us know whether you could solve the issue. 

Best wishes
Stefanie

**Comment by CarlaCristinaUranga** [comment]
Hi Stefanie,

I realized the other day that the networks are different because I am
filtering my data according to highest variance. One question for you about
this. I am interested in plotting those samples that have the highest
variance because they would be the most interesting to me, however, I see
that when I reduce this parameter, I get less values plotted. I am just
curious as to the parameter. Usually if you have a higher variance, the
actual number is higher. Here it seems that the "highestVar" parameter is
lower for those samples with higher variances. Am I interpreting this
incorrectly? Thank you again and I am definitely enjoying NetCoMi and want
to learn more about the mathematical underpinnings of how it works. I hope
you are staying healthy!

Best wishes,

Carla Uranga

**Comment by stefpeschel** [comment]
Dear Carla, 

the "highestVar" argument works as follows:

`netConstruct(data, 
filtTax = "highestVar",
filtTaxPar = list(highestVar = 50), ...)
`
(without any other filters, and no NAs or taxa with an overall sum of zero in the data) leads to a count matrix with 50 taxa. These are the 50 taxa with highest variance.

Reducing the "highestVar" argument to 30, for instance, leads to a count matrix with 30 taxa. 

BTW, the "highestFreq" argument has a similar behaviour: It selects the x taxa with highest frequency. 

Does that answer your question?

Best wishes
Stefanie

**Comment by CarlaCristinaUranga** [comment]
Yes, it does. You are awesome. Thank you!

Best regards,

Carla
