### ISSUE TITLE
Issue with installation

### ISSUE THREAD

**Issue by adahal123** [stefpeschel/NetCoMi#131]
**See below***

> devtools::install_github("stefpeschel/NetCoMi", 
+                          dependencies = c("Depends", "Imports", "LinkingTo"),
+                          repos = c("https://cloud.r-project.org/",
+                                    BiocManager::repositories()))
Downloading GitHub repo stefpeschel/NetCoMi@HEAD
'getOption("repos")' replaces Bioconductor standard repositories, see 'help("repositories", package = "BiocManager")' for
details.
Replacement repositories:
    CRAN: https://cran.rstudio.com/
Error: Failed to install 'NetCoMi' from GitHub:
  Unknown remote type: bioc
  Invalid bioc repo: metagenomeSeq@1.47.0

**If I try to install the dependencies:** 

> devtools::install_github("zdk123/SpiecEasi")

Downloading GitHub repo zdk123/SpiecEasi@HEAD
── R CMD build ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/private/var/folders/2s/bs5ct1_d2w3f1m_n8lqc0tw40000gq/T/Rtmp2nDddh/remotes2a20788a45a8/zdk123-SpiecEasi-5f396da/DESCRIPTION’ (429ms)
─  preparing ‘SpiecEasi’:
✔  checking DESCRIPTION meta-information
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts (452ms)
─  checking for empty or unneeded directories
   Removed empty directory ‘SpiecEasi/inst’
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘SpiecEasi_1.1.3.tar.gz’
   
Installing package into ‘/Users/dahsx6/Library/R/x86_64/4.4/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘SpiecEasi’ ...
** using staged installation
** libs
using C++ compiler: ‘Apple clang version 15.0.0 (clang-1500.3.9.4)’
using C++11
using SDK: ‘MacOSX14.4.sdk’
clang++ -arch x86_64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Users/dahsx6/Library/R/x86_64/4.4/library/Rcpp/include' -I'/Users/dahsx6/Library/R/x86_64/4.4/library/RcppArmadillo/include' -I/opt/R/x86_64/include    -fPIC  -falign-functions=64 -Wall -g -O2   -c ADMM.cpp -o ADMM.o
clang++ -arch x86_64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Users/dahsx6/Library/R/x86_64/4.4/library/Rcpp/include' -I'/Users/dahsx6/Library/R/x86_64/4.4/library/RcppArmadillo/include' -I/opt/R/x86_64/include    -fPIC  -falign-functions=64 -Wall -g -O2   -c RcppExports.cpp -o RcppExports.o
clang++ -arch x86_64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Users/dahsx6/Library/R/x86_64/4.4/library/Rcpp/include' -I'/Users/dahsx6/Library/R/x86_64/4.4/library/RcppArmadillo/include' -I/opt/R/x86_64/include    -fPIC  -falign-functions=64 -Wall -g -O2   -c matops.cpp -o matops.o
clang++ -arch x86_64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Users/dahsx6/Library/R/x86_64/4.4/library/Rcpp/include' -I'/Users/dahsx6/Library/R/x86_64/4.4/library/RcppArmadillo/include' -I/opt/R/x86_64/include    -fPIC  -falign-functions=64 -Wall -g -O2   -c sqrtNewton.cpp -o sqrtNewton.o
clang++ -arch x86_64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Users/dahsx6/Library/R/x86_64/4.4/library/Rcpp/include' -I'/Users/dahsx6/Library/R/x86_64/4.4/library/RcppArmadillo/include' -I/opt/R/x86_64/include    -fPIC  -falign-functions=64 -Wall -g -O2   -c svthresh.cpp -o svthresh.o
clang++ -arch x86_64 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/x86_64/lib -o SpiecEasi.so ADMM.o RcppExports.o matops.o sqrtNewton.o svthresh.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/opt/gfortran/lib/gcc/x86_64-apple-darwin20.0/12.2.0 -L/opt/gfortran/lib -lgfortran -lquadmath -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: search path '/opt/gfortran/lib/gcc/x86_64-apple-darwin20.0/12.2.0' not found
ld: warning: search path '/opt/gfortran/lib' not found
ld: library 'gfortran' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [SpiecEasi.so] Error 1
ERROR: compilation failed for package ‘SpiecEasi’
* removing ‘/Users/dahsx6/Library/R/x86_64/4.4/library/SpiecEasi’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/2s/bs5ct1_d2w3f1m_n8lqc0tw40000gq/T//Rtmp2nDddh/file2a203de3566b/SpiecEasi_1.1.3.tar.gz’ had non-zero exit status

Tried a bunch of different things, can't seem to figure out what to do.

**Comment by elmonten** [comment]
I'm getting the same issue... :S

**Comment by stefpeschel** [comment]
Hi!
[This](https://github.com/zdk123/SpiecEasi/issues/253) issue seems to cover your problem with the SpiecEasi package. 
I'm working on a solution for the bioc packages. However, it would be good if you were able to install SpiecEasi as a first step.

**Comment by stefpeschel** [comment]
I added a new branch "fix_installation" with changes in the DESCRIPTION file. 
Could you please try if you're able to install NetCoMi from this branch using the following command?
```
devtools::install_github("stefpeschel/NetCoMi", 
                         ref = "fix_installation",
                         repos = c("https://cloud.r-project.org/",
                                   BiocManager::repositories()))
```
I did some test runs on my Windows PC with an empty library, but I cannot test on a Mac.

**Comment by stefpeschel** [comment]
Thanks for the feedback! Glad to hear it works. 
I will merge the branch into main then.
