### ISSUE TITLE
error with featVecCol

### ISSUE THREAD

**Issue by AndreaQ7** [stefpeschel/NetCoMi#14]
Hello everyone and congratulation for this interesting package. 
I am getting an error when trying to follow the tutorial to add phyla colors to my network. Particularly, when using the same commands in the turotial I get this error message:

```
Error in plot.microNetProps(props_single3, layout = "spring", repulsion = 0.6,  : 
  all(colnames(adja1) %in% names(featVecCol)) is not TRUE    
```

But i do not understand it very well can you give me an hand please? thanks

**Comment by stefpeschel** [comment]
Hey Andrea,

thanks for your interest in using NetCoMi!

When using the "featVecCol" argument, it is important that the elements of this vector have the same names as the taxa (dimnames of the adjacency matrix). 

I just reran the part of the tutorial you mentioned and don't get this error. So, please ensure that the three lines before the function call are executed correctly. In particular the following line is important:
`names(phyla) <- taxtab[, "Rank6"]`

Maybe it helps to double-check whether the names are equal before you call the plot function. 

Please let me know if you could solve the problem. 

Kind regards
Stefanie

**Comment by AndreaQ7** [comment]
Thanks a lot. Indeed, looking in the taxtab the error was that it has genus with the "g__" before and that not allow to recognize that was the same name.
