### ISSUE TITLE
cran/bioconductor?

### ISSUE THREAD

**Issue by nick-youngblut** [stefpeschel/NetCoMi#19]
While this benchmark isn't currently attained by similar software (e.g., https://github.com/zdk123/SpiecEasi/issues/90), are you planning on publishing NetCoMi on CRAN/Bioconductor? Conda would also be great, as done for SpiecEasi

**Comment by stefpeschel** [comment]
Hey Nick,
Thanks for your suggestion! Publishing NetCoMi on one or more of these  platforms is planned at some point but not in the near future. 
Best, Stefanie

**Comment by adrientaudiere** [comment]
Hi @stefpeschel,
Is submission to CRAN still on the agenda? I can help a little with this. I develop and maintain the [MiscMetabar](https://adrientaudiere.github.io/MiscMetabar/) package, and your package may add very useful insight into my metabarcoding analysis. 

Best,
Adrien

**Comment by stefpeschel** [comment]
Hi Adrien,
Thanks for the offer. Submission to CRAN is not planned. Maybe, NetCoMi will be sent to Bioconductor at some point. However, it currently doesn't make much sense since two of the main dependencies (SpiecEasi and SPRING) are only available on GitHub.

**Comment by adrientaudiere** [comment]
Thanks for your prompt answer. That makes sense.
