### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by yugi1001** [stefpeschel/NetCoMi#30]
Hi,
I have been encountering an error while trying to install the package. can you please help. Thanks
> install_github("stefpeschel/NetCoMi")
Downloading GitHub repo stefpeschel/NetCoMi@HEAD
Error: Failed to install 'NetCoMi' from GitHub:
  Command failed (128)
In addition: Warning message:
In system(full, intern = TRUE, ignore.stderr = quiet) :
  running command ''/usr/bin/git' ls-remote https://git.bioconductor.org/packages/Biobase RELEASE_3_14 2>/dev/null' had status 128

> sessionInfo()
R version 4.0.3 (2020-10-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1

**Comment by stefpeschel** [comment]
Hey, 

I have just successfully installed NetCoMi on a Linux server with the following specifications:

```
R version 4.0.4 (2021-02-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04 LTS
```
So, the installation should generally work on Linux. 

I would suggest to install NetCoMi's dependencies manually using the following code:

```
if(!requireNamespace("BiocManager", quietly = TRUE)){
  utils::install.packages("BiocManager")
}

BiocManager::install(pkgs = c("Biobase", "doSNOW", "fdrtool", "filematrix",
                              "foreach", "graphics", "grDevices", "gtools",
                              "huge", "igraph", "MASS", "Matrix", "phyloseq",
                              "pulsar", "qgraph", "Rdpack", "snow", "SPRING",
                              "stats", "utils", "vegan", "WGCNA"))

devtools::install_github("GraceYoon/SPRING")
devtools::install_github("zdk123/SpiecEasi")

devtools::install_github("stefpeschel/NetCoMi", 
                         dependencies = c("Depends", "Imports"),
                         repos = c("https://cloud.r-project.org/",
                                   BiocManager::repositories()))
```

Since in your case, there might be a problem with the Biobase package, you could also start with installing only the Biobase package and see if you encounter any problems.

Please let me know if you still have problems with the installation. 

Best,
Stefanie

**Comment by stefpeschel** [comment]
I will close this issue now. Feel free to reopen it if there are still intallation problems.

**Comment by lianetd** [comment]
hello,
I have been encountering an error while trying to install the package. can you please help. Thanks
Downloading GitHub repo stefpeschel/NetCoMi@HEAD
Error: Failed to install 'NetCoMi' from GitHub:
  Git does not seem to be installed on your system.
then i traite with this code
if(!requireNamespace("BiocManager", quietly = TRUE)){
  utils::install.packages("BiocManager")
}

BiocManager::install(pkgs = c("Biobase", "doSNOW", "fdrtool", "filematrix",
                              "foreach", "graphics", "grDevices", "gtools",
                              "huge", "igraph", "MASS", "Matrix", "phyloseq",
                              "pulsar", "qgraph", "Rdpack", "snow", "SPRING",
                              "stats", "utils", "vegan", "WGCNA"))

devtools::install_github("GraceYoon/SPRING")
devtools::install_github("zdk123/SpiecEasi")

devtools::install_github("stefpeschel/NetCoMi", 
                         dependencies = c("Depends", "Imports"),
                         repos = c("https://cloud.r-project.org/",
                                   BiocManager::repositories()))
but the program was not installed

**Comment by Sarbu4all** [comment]
I also had error with install_github("stefpeschel/NetCoMi"). After installing gfortran (https://cran.r-project.org/), the issue was solved! As suggested, I installed SPRING and SpiecEasi first and then NetCoMi.

**Comment by Apatzingan1** [comment]
Hi I have the same problem  ---- Error: Failed to install 'NetCoMi' from GitHub:
                                                 Git does not seem to be installed on your system
I install NetCoMi's dependencies manually, and the Error shows only in:
devtools::install_github("stefpeschel/NetCoMi", dependencies = c("Depends", "Imports"), repos = c("https://cloud.r-project.org/", BiocManager::repositories()))
