### ISSUE TITLE
Issue with netConstruct with knn algorithm

### ISSUE THREAD

**Issue by hanghu1024** [stefpeschel/NetCoMi#37]
Hi! 

I am trying to construct the graph with knn algorithm. My data is a pre-computed association matrix,  and my parameters are listed below:
```
net <- netConstruct(data = matrix, 
                    dataType = "correlation", 
                    sparsMethod = "knn",
                    kNeighbor = 10,
                    knnMutual = FALSE)
```
But I get the error message:
```
Sparsify associations via 'knn' ... Done.
Error in if (all(x.tmp <= 1)) { : missing value where TRUE/FALSE needed
In addition: Warning message:
In sqrt(0.5 * (1 - xvec)) : NaNs produced
```
You give an tutorial example for knn using count data, but does it work for association matrix? If so, is there a way to fix this bug? In addition, the default value for kNeighbor is 3L, what's the point for "L" here? I am using version 1.0.2, and I got some success with threshold method for this data. 

Many thanks!

Hang

**Comment by stefpeschel** [comment]
Dear Hang,

The knn algorithm works only for dissimilarities, not for associations. So, your matrix must be a dissimilarity matrix and you have to set the "datatype" argument to "dissimilarity". In the resulting network, nodes will be the samples, not the taxa. 

Best, 
Stefanie

**Comment by hanghu1024** [comment]
Hello Stefanie, 

Got it, thanks!

Best,
Hang
