### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by e-merc** [stefpeschel/NetCoMi#39]
Hi,

Trying to install this in R 4.1.2 and endlessly getting errors. I've gone through closed issues and tried various methods, but it keeps spitting back errors when installing. Any input on how to fix this? It does not work if I try to install SpiecEasi or SPRING separately.

Using github PAT from envvar GITHUB_PAT
Downloading GitHub repo stefpeschel/NetCoMi@HEAD
'getOption("repos")' replaces Bioconductor standard repositories, see '?repositories' for details

replacement repositories:
    CRAN: https://cran.rstudio.com/

These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                        
2: CRAN packages only         
3: None                       
4: cli (3.1.0 -> 3.1.1) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 3
Downloading GitHub repo zdk123/SpiecEasi@HEAD
✓  checking for file ‘/private/var/folders/9_/tg2nr0d945v54g87153420bw0000gn/T/RtmphbGZp6/remotes2e8c113a4c11/zdk123-SpiecEasi-c463727/DESCRIPTION’ (3.3s)
─  preparing ‘SpiecEasi’:
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts (657ms)
─  checking for empty or unneeded directories
   Removed empty directory ‘SpiecEasi/inst’
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘SpiecEasi_1.1.2.tar.gz’
   
* installing *source* package ‘SpiecEasi’ ...
** using staged installation
** libs
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c ADMM.cpp -o ADMM.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c matops.cpp -o matops.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c sqrtNewton.cpp -o sqrtNewton.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.1/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.1/Resources/library/RcppArmadillo/include' -I/usr/local/include   -fPIC  -Wall -g -O2  -c svthresh.cpp -o svthresh.o
clang++ -mmacosx-version-min=10.13 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o SpiecEasi.so ADMM.o RcppExports.o matops.o sqrtNewton.o svthresh.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0 -L/usr/local/gfortran/lib -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [SpiecEasi.so] Error 1
ERROR: compilation failed for package ‘SpiecEasi’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/SpiecEasi’
Warning in i.p(...) :
  installation of package ‘/var/folders/9_/tg2nr0d945v54g87153420bw0000gn/T//RtmphbGZp6/file2e8ca57f8ed/SpiecEasi_1.1.2.tar.gz’ had non-zero exit status
Downloading GitHub repo GraceYoon/SPRING@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                                      
2: CRAN packages only                       
3: None                                     
4: mixedCCA (1.4.6 -> 71da2060b...) [GitHub]
5: cli      (3.1.0 -> 3.1.1       ) [CRAN]  

Enter one or more numbers, or an empty line to skip updates: 3
Downloading GitHub repo zdk123/SpiecEasi@HEAD
Skipping SpiecEasi, it is already being installed
Downloading GitHub repo zdk123/SpiecEasi@HEAD
Skipping SpiecEasi, it is already being installed
✓  checking for file ‘/private/var/folders/9_/tg2nr0d945v54g87153420bw0000gn/T/RtmphbGZp6/remotes2e8c3fb89924/GraceYoon-SPRING-470fe2d/DESCRIPTION’ (9.8s)
─  preparing ‘SPRING’: (529ms)
✓  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts (620ms)
─  checking for empty or unneeded directories
─  building ‘SPRING_1.0.4.tar.gz’
   
ERROR: dependency ‘SpiecEasi’ is not available for package ‘SPRING’
* removing ‘/Library/Frameworks/R.framework/Versions/4.1/Resources/library/SPRING’
Warning in i.p(...) :
  installation of package ‘/var/folders/9_/tg2nr0d945v54g87153420bw0000gn/T//RtmphbGZp6/file2e8c770041d7/SPRING_1.0.4.tar.gz’ had non-zero exit status
Downloading GitHub repo zdk123/SpiecEasi@HEAD
Skipping SpiecEasi, it is already being installed
Downloading GitHub repo GraceYoon/SPRING@HEAD
Skipping SPRING, it is already being installed
✓  checking for file ‘/private/var/folders/9_/tg2nr0d945v54g87153420bw0000gn/T/RtmphbGZp6/remotes2e8c34c3ffe3/stefpeschel-NetCoMi-55cc678/DESCRIPTION’ (655ms)
─  preparing ‘NetCoMi’: (1.3s)
✓  checking DESCRIPTION meta-information
─  installing the package to process help pages
         -----------------------------------
   ERROR: dependencies ‘SpiecEasi’, ‘SPRING’ are not available for package ‘NetCoMi’
─  removing ‘/private/var/folders/9_/tg2nr0d945v54g87153420bw0000gn/T/RtmpW78sBw/Rinst311c204a035b/NetCoMi’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'NetCoMi' from GitHub:
  System command 'R' failed, exit status: 1, stdout & stderr were printed

**Comment by stefpeschel** [comment]
Hey, 

You first have to get SpiecEasi installed since SPRING depends on SpiecEasi, and NetCoMi on both packages. 

There are some warnings in your output and I assume they give a hint on why SpiecEasi can't be installed on your computer: 
```
ld: warning: directory not found for option '-L/usr/local/gfortran/lib/gcc/x86_64-apple-darwin18/8.2.0'
ld: warning: directory not found for option '-L/usr/local/gfortran/lib'
ld: library not found for -lgfortran
```

I searched the SpiecEasi issues for "gfortran" and there are several issues providing solutions for getting SpiecEasi installed on Mac. In [issue 164](https://github.com/zdk123/SpiecEasi/issues/164), for instance, is referred to a point in SpiecEasi's [readme ](https://github.com/zdk123/SpiecEasi#osx-users), where an additional step for Mac users is suggested.

On stackoverflow, there's also a similar [issue](https://stackoverflow.com/questions/58610155/problem-installing-r-package-ld-warning-directory-not-found-for-option) where you could find an answer. I would, however, search the SpiecEasi issues for a solution first. 

Hope you are finally able to install NetCoMi. 
Best,
Stefanie

**Comment by e-merc** [comment]
Hi Stefanie,

Thanks for this insight! I was able to download NetCoMi and dependencies by downloading the gfortan binaries directly from CRAN (https://cran.r-project.org/bin/macosx/tools/) for anyone else who may run into this on Mac. 

Thanks again!
