### ISSUE TITLE
Error in installing NetCoMi

### ISSUE THREAD

**Issue by DzungNguyen181** [stefpeschel/NetCoMi#52]
Hi, I've been trying to install NetCoMi to analyze my microbiome data. However, I've ran into this error:

![image](https://user-images.githubusercontent.com/102470900/172064867-7834938d-c8a2-4488-9775-4eb94efd067d.png)

I've successfully installed "devtools" and "BiocManager" before, yet I had a problem installing SpiecEasi package. 

![image](https://user-images.githubusercontent.com/102470900/172064698-abbff6e7-e55f-4b3f-8781-7d54f4c1ce39.png)

I'm wondering if this is the reason why I cannot install NetCoMi?
I'm looking forward to your help. Thank you already!!

**Comment by stefpeschel** [comment]
Hey, 
Sorry for the late reply. 
Could you please try installing SpiecEasi manually? See also issue #27 for instructions. 
Best,
Stefanie
