### ISSUE TITLE
Error installation

### ISSUE THREAD

**Issue by carolynePearl** [stefpeschel/NetCoMi#7]
Hello,

I have tried to install this package for 5 days no with continuous errors;

> gcc -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I"/Users/bioinformaticslabcomp1/Library/R/3.6/library/Rcpp/include" -I"/Users/bioinformaticslabcomp1/Library/R/3.6/library/RcppArmadillo/include" -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk -I/usr/local/include -fopenmp  -fPIC  -Wall -g -O2  -c C_SparCC.cpp -o C_SparCC.o
E> clang: error: unsupported option '-fopenmp'
E> make: *** [C_SparCC.o] Error 1
E> ERROR: compilation failed for package ‘NetCoMi’
E> * removing ‘/private/var/folders/rh/gg65ng2n2c150mh6_4slmpyw0000gn/T/RtmpJFpM9T/Rinst586549fefcb/NetCoMi’
E>       -----------------------------------
E> ERROR: package installation failed

I have tried to install most of the packages manually. How can you help.

**Comment by blsteven** [comment]
I am having the same issue. Any help is much appreciated

**Comment by stefpeschel** [comment]
Hello, 

Sorry for my late response! 

The Rcpp and RcppArmadillo packages, which seem to cause the error, are needed since NetCoMi's SparCC function is implemented in C++. Other users already working with NetCoMi didn't have problems installing these two packages, so could you please let me know which operating system you are working with? 

Until I've found a solution, I'll replace the current function by the SparCC implementation of SpiecEasi so that NetCoMi can at least be installed.

**Comment by carolynePearl** [comment]
so i am using Mac OS version 10.14.6. The Rcpp and RcppArmadillo packages are already installed. Actually i load them first before i ran the install.

**Comment by blsteven** [comment]
Still having the same problem. Mac OSX 10.15.6

**Comment by stefpeschel** [comment]
I created a new branch "hotfix-1.0.2" that uses sparcc() from SpiecEasi so that the Rcpp packages are no longer needed. 

This version can be installed using 
devtools::install_github("stefpeschel/NetCoMi", force = TRUE, ref = "hotfix-1.0.2")

Please let me know whether installing NetCoMi works with this version. Then, I can merge it into master. 

Best wishes
Stefanie

**Comment by carolynePearl** [comment]
let me try

**Comment by carolynePearl** [comment]
hello,

am still getting an error; Here it is

> devtools::install_github("stefpeschel/NetCoMi", force = TRUE, ref = "hotfix-1.0.2")
Downloading GitHub repo stefpeschel/NetCoMi@hotfix-1.0.2
Skipping 4 packages not available: AnnotationDbi, GO.db, preprocessCore, impute
Skipping 1 packages ahead of CRAN: data.table
✓  checking for file ‘/private/var/folders/rh/gg65ng2n2c150mh6_4slmpyw0000gn/T/RtmpIz2Acl/remotes340631e46d0/stefpeschel-NetCoMi-6f36bc8/DESCRIPTION’ (3.9s)
─  preparing ‘NetCoMi’: (923ms)
✓  checking DESCRIPTION meta-information ...
─  cleaning src
─  installing the package to process help pages (339ms)
         -----------------------------------
─  installing *source* package ‘NetCoMi’ ...
   ** using staged installation
   ** libs
   Warning: no source files found
   ** R
   ** inst
   ** byte-compile and prepare package for lazy loading
   ** help
   Loading required namespace: NetCoMi
   
   Registered S3 methods overwritten by 'BDgraph':
     method    from
     plot.sim  huge
     print.sim huge
   Registered S3 method overwritten by 'GGally':
     method from   
     +.gg   ggplot2
   sROC 0.1-2 loaded
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   Loading required namespace: NetCoMi
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   Loading required namespace: NetCoMi
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   Loading required namespace: NetCoMi
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   Loading required namespace: NetCoMi
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   Loading required namespace: NetCoMi
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   Loading required namespace: NetCoMi
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   Loading required namespace: NetCoMi
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   Loading required namespace: NetCoMi
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   Loading required namespace: NetCoMi
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   Loading required namespace: NetCoMi
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   Loading required namespace: NetCoMi
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   Loading required namespace: NetCoMi
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   Loading required namespace: NetCoMi
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   Loading required namespace: NetCoMi
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   Loading required namespace: NetCoMi
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   Loading required namespace: NetCoMi
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   Loading required namespace: NetCoMi
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   Loading required namespace: NetCoMi
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   Loading required namespace: NetCoMi
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   Loading required namespace: NetCoMi
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   Loading required namespace: NetCoMi
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   Loading required namespace: NetCoMi
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   Loading required namespace: NetCoMi
   Failed with error:  ‘shared object ‘NetCoMi.so’ not found’
   *** installing help indices
   ** building package indices
   ** testing if installed package can be loaded from temporary location
   Error: package or namespace load failed for ‘NetCoMi’ in library.dynam(lib, package, package.lib):
    shared object ‘NetCoMi.so’ not found
   Error: loading failed
   Execution halted
   ERROR: loading failed
─  removing ‘/private/var/folders/rh/gg65ng2n2c150mh6_4slmpyw0000gn/T/RtmpfTzrYs/Rinst17979de1a08/NetCoMi’
         -----------------------------------
   ERROR: package installation failed
Error: Failed to install 'NetCoMi' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr (last 10 lines):
E> ** building package indices
E> ** testing if installed package can be loaded from temporary location
E> Error: package or namespace load failed for ‘NetCoMi’ in library.dynam(lib, package, package.lib):
E>  shared object ‘NetCoMi.so’ not found
E> Error: loading failed
E> Execution halted
E> ERROR: loading failed
E> * removing ‘/private/var/folders/rh/gg65ng2n2c150mh6_4slmpyw0000gn/T/RtmpfTzrYs/Rinst17979de1a08/NetCoMi’
E>       -----------------------------------
E> ERROR: package installation failed

**Comment by blsteven** [comment]
same error here....sorry

**Comment by stefpeschel** [comment]
Sorry for the delay. Took me a while to fix these errors. Could you please test whether the new version works? 
I had the same errors after the updates but now it works for me. I also ran devtools::check(), but I can only test the package on Windows and Linux.

**Comment by carolynePearl** [comment]
Thank you. it successfully worked.
