### ISSUE TITLE
netcompare error in unserialize

### ISSUE THREAD

**Issue by lixiaopi1985** [stefpeschel/NetCoMi#71]
Hi Stef,

I encountered error when using netCompare.

```
netITS.spie = netConstruct(data = fITS.metam,
                           data2 = fITS.no,
                           measure = "spieceasi",
                           measurePar = list(lambda.min.ratio=1e-2, nlambda=20, pulsar.params=list(rep.num=50)),
                           filtTax = "highestFreq",
                           filtTaxPar = list(highestFreq=500),
                           zeroMethod = "multRepl",
                           normMethod = "clr",
                           sparsMethod = "threshold",
                           cores = parallel::detectCores()/2,
                           thresh = 0.6,
                           verbose = 3,
                           seed = 123456)
```

```
netAnaITS = netAnalyze(netITS.spie,
                       # centrLCC = TRUE,
                       hubPar = c("degree", "between", "closeness", "eigenvector"),
                       clustMethod = "cluster_fast_greedy",
                       lnormFit = T,
                       normDeg = T,
                       normBetw = T,
                       normClose = T,
                       normEigen = T)
```

```
netCompareITS = netCompare(netAnaITS,
                           permTest = T,
                           storeAssoPerm = T,
                           fileStoreAssoPerm = "./fITS_assoPerm_nperm1000_updated",
                           nPerm = 1000,
                           cores = 30,
                           seed = 321)
```
```
XEC 
  |============            |   6%corrupted double-linked list
Error in unserialize(socklist[[n]]) : error reading from connection

 *** caught segfault ***
address (nil), cause 'unknown'
```
It was run on a Ubuntu 18.04. 

Could you take a look at the issue?

Best,
Xiao

**Comment by stefpeschel** [comment]
Hi Xiao, 

This error has occurred before in other packages and seems to be a general problem with the worker. The answers given in this thread will hopefully help to solve the issue:
[https://stackoverflow.com/questions/24327137/error-in-unserializesocklistn-error-reading-from-connection-on-unix](https://stackoverflow.com/questions/24327137/error-in-unserializesocklistn-error-reading-from-connection-on-unix)

Best,
Stefanie

**Comment by lixiaopi1985** [comment]
> Hi Xiao,
> 
> This error has occurred before in other packages and seems to be a general problem with the worker. The answers given in this thread will hopefully help to solve the issue: https://stackoverflow.com/questions/24327137/error-in-unserializesocklistn-error-reading-from-connection-on-unix
> 
> Best, Stefanie

I don't know enough about parallel processing so I lowered the number of taxa (highestFreq) to 300 and it worked fine. Thanks Stefanie.
