### ISSUE TITLE
problems about installation

### ISSUE THREAD

**Issue by YuT95** [stefpeschel/NetCoMi#75]
Hi I am not able to install NetCoMi in R studio with mac. the errors are as follows. I have tried all the answers under the issues but it didn't work. thanks!

Error: Failed to install 'NetCoMi' from GitHub:
  ! System command 'R' failed
In addition: Warning messages:
1: In i.p(...) :
  installation of package ‘/var/folders/wx/xprxkc2j53j4qqfk46d5cy300000gn/T//Rtmp332LmE/filee78e3eb63f10/SpiecEasi_1.1.2.tar.gz’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘/var/folders/wx/xprxkc2j53j4qqfk46d5cy300000gn/T//Rtmp332LmE/filee78e41a66039/mixedCCA_1.6.2.tar.gz’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘/var/folders/wx/xprxkc2j53j4qqfk46d5cy300000gn/T//Rtmp332LmE/filee78e3a80d0a9/SPRING_1.0.4.tar.gz’ had non-zero exit status

**Comment by stefpeschel** [comment]
Hi @YuT95. 
Apparently, the three packages SpiecEasi, SPRING, and mixedCCA cannot be installed automatically because they are only available on GitHub. 
Please install them manually in advance with: 

```
devtools::install_github("zdk123/SpiecEasi")
devtools::install_github("irinagain/mixedCCA")
devtools::install_github("GraceYoon/SPRING")
```

The order is important because SPRING depends on mixedCCA and SpiecEasi.

**Comment by YuT95** [comment]
Hi Stefanie,
Thanks for your reply.
but when I run it, errors are as follows:


R version 4.2.2 (2022-10-31) -- "Innocent and Trusting"
Copyright (C) 2022 The R Foundation for Statistical Computing
Platform: aarch64-apple-darwin20 (64-bit)


R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.


  Natural language support but running in an English locale


R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.


Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.


> library(devtools)
Loading required package: usethis
> devtools::install_github("zdk123/SpiecEasi") 
Downloading GitHub repo ***@***.***
✔  checking for file ‘/private/var/folders/wx/xprxkc2j53j4qqfk46d5cy300000gn/T/RtmpdVzYNU/remotesd01e75318fc0/zdk123-SpiecEasi-41448ad/DESCRIPTION’ ...
─  preparing ‘SpiecEasi’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Removed empty directory ‘SpiecEasi/inst’
─  looking to see if a ‘data/datalist’ file should be added
─  building ‘SpiecEasi_1.1.2.tar.gz’
   
* installing *source* package ‘SpiecEasi’ ...
** using staged installation
** libs
clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c ADMM.cpp -o ADMM.o
clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c matops.cpp -o matops.o
clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c sqrtNewton.cpp -o sqrtNewton.o
clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include   -fPIC  -falign-functions=64 -Wall -g -O2  -c svthresh.cpp -o svthresh.o
clang++ -arch arm64 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o SpiecEasi.so ADMM.o RcppExports.o matops.o sqrtNewton.o svthresh.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/opt/R/arm64/gfortran/lib/gcc/aarch64-apple-darwin20.6.0/12.0.1 -L/opt/R/arm64/gfortran/lib -lgfortran -lemutls_w -lquadmath -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/opt/R/arm64/gfortran/lib/gcc/aarch64-apple-darwin20.6.0/12.0.1'
ld: warning: directory not found for option '-L/opt/R/arm64/gfortran/lib'
ld: library not found for -lemutls_w
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [SpiecEasi.so] Error 1
ERROR: compilation failed for package ‘SpiecEasi’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/SpiecEasi’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/wx/xprxkc2j53j4qqfk46d5cy300000gn/T//RtmpdVzYNU/filed01e3e6530ad/SpiecEasi_1.1.2.tar.gz’ had non-zero exit status
> devtools::install_github("irinagain/mixedCCA") 
Downloading GitHub repo ***@***.***
✔  checking for file ‘/private/var/folders/wx/xprxkc2j53j4qqfk46d5cy300000gn/T/RtmpdVzYNU/remotesd01e6e1bab77/irinagain-mixedCCA-4c2b63f/DESCRIPTION’ ...
─  preparing ‘mixedCCA’:
✔  checking DESCRIPTION meta-information ...
─  cleaning src
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘mixedCCA_1.6.2.tar.gz’
   
* installing *source* package ‘mixedCCA’ ...
** using staged installation
** libs
clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c RcppExports.cpp -o RcppExports.o
clang++ -arch arm64 -std=gnu++11 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG  -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/Rcpp/include' -I'/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/RcppArmadillo/include' -I/opt/R/arm64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c find_w1w2.cpp -o find_w1w2.o
clang++ -arch arm64 -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/opt/R/arm64/lib -o mixedCCA.so RcppExports.o find_w1w2.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/opt/R/arm64/gfortran/lib/gcc/aarch64-apple-darwin20.6.0/12.0.1 -L/opt/R/arm64/gfortran/lib -lgfortran -lemutls_w -lquadmath -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
ld: warning: directory not found for option '-L/opt/R/arm64/gfortran/lib/gcc/aarch64-apple-darwin20.6.0/12.0.1'
ld: warning: directory not found for option '-L/opt/R/arm64/gfortran/lib'
ld: library not found for -lemutls_w
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [mixedCCA.so] Error 1
ERROR: compilation failed for package ‘mixedCCA’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/mixedCCA’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/library/mixedCCA’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/wx/xprxkc2j53j4qqfk46d5cy300000gn/T//RtmpdVzYNU/filed01e5a964a1a/mixedCCA_1.6.2.tar.gz’ had non-zero exit status
Best,
Yu
















At 2022-11-22 16:11:41, "Stefanie Peschel" ***@***.***> wrote:

Hi @YuT95.
Apparently, the three packages SpiecEasi, SPRING, and mixedCCA cannot be installed automatically because they are only available on GitHub.
Please install them manually in advance with:

devtools::install_github("zdk123/SpiecEasi")
devtools::install_github("irinagain/mixedCCA")
devtools::install_github("GraceYoon/SPRING")


The order is important because SPRING depends on mixedCCA and SpiecEasi.

**Comment by stefpeschel** [comment]
Sorry, I forgot that mixedCCA is available on CRAN as well. So please install the package from CRAN as first step:
`install.packages("mixedCCA")`

Then, install SpiecEasi:
`devtools::install_github("zdk123/SpiecEasi")`
and SPRING as last step:
`devtools::install_github("GraceYoon/SPRING")`

I assume it's a general problem with installing packages from GitHub on Mac. Please ensure that you're using the latest `devtools` version.

**Comment by stefpeschel** [comment]
There is already an open issue for SpiecEasi: [https://github.com/zdk123/SpiecEasi/issues/225](https://github.com/zdk123/SpiecEasi/issues/225). This seems to be the same error you get. 
You could maybe comment that you have the same issue. 

I'm really sorry but this issue is not directly NetCoMi related and I don't know how to solve it either.

**Comment by daydream-boost** [comment]
Hi, @YuT95 
You can use conda/mamba to install NetCoMi easily on MacOS.
