### ISSUE TITLE
problems about installation

### ISSUE THREAD

**Issue by TSH1993** [stefpeschel/NetCoMi#82]
Hi,I am not able to install NetCoMi in R studio with windows11. the errors are as follows.

Error: Failed to install 'unknown package' from GitHub:
  schannel: failed to receive handshake, SSL/TLS connection failed

**Comment by stefpeschel** [comment]
Hi,
I googled a bit and this seems to be a GitHub-related issue.

Have you devtools and Rtools installed? 
If not: devtools can be installed from CRAN directly, and [this](https://www.rdocumentation.org/packages/installr/versions/0.23.4/topics/install.Rtools) function can be used to install Rtools on Windows. Both are needed to install R packages from GitHub.
