### ISSUE TITLE
How to interpret SPRING correlation values?

### ISSUE THREAD

**Issue by antonkratz** [stefpeschel/NetCoMi#84]
Is there a way to intuitively interpret SPRING values? I note that the vast majority of the american gut microbiome example data is somewhere between -0.1 and 0.2.

What are the possible extrema?

The values seem somehow low?! Does this mean that in the example data the OTUs do not correlate much according to SPRING?

**Comment by muellsen** [comment]
Hi Anton, 
the original SPRING publication is here: https://www.frontiersin.org/articles/10.3389/fgene.2019.00516/full 
The values are essentially partial correlation coefficients (so are in the interval [-1,1]. So, here, from the small subset of American Gut (a few hundred samples) there are only small partial correlation estimated...
