### ISSUE TITLE
In a few cases, class assignment by DISCORDANT seems to contradict the associations from the two input networks

### ISSUE THREAD

**Issue by antonkratz** [stefpeschel/NetCoMi#85]
My workflow involves SPRING followed by DISCORDANT to identify differentially associated OTUs in a network measured in two states. I observe a few edges where the class assignment by DISCORDANT seems to contradict the associations from
the two input networks. That is, I have an OTU which is completely disconnected in state A. The same OTU has connections to other OTUs in state B, and these connections all happen to be negative. My expectation is that in the resulting differential network, the class should always by 4, i.e. from 0 to -. Yet, I sometimes observe class 7 as well, from 0 to +. For example:

- OTU<sub>1</sub>, OTU<sub>2</sub> are not connected in state A.
- OTU<sub>1</sub>, OTU<sub>2</sub> are connected by an edge score of -0.1 in state B.

In the resulting diff. network, the edge between OTU<sub>1</sub> and OTU<sub>2</sub> gets assigned class 7 (0 to +) in the `classMat`, which I think is a contradiction, shouldn't it be rather class 4 (0 to -)?

For a different connection (OTU<sub>1</sub> to OTU<sub>3</sub>, not existent in state A, with a score of -0.21 in state B) I observe class 4 (0 to -) as expected.

Shouldn't "from zero to some negative score" (if it makes it into the diff. network) always get class 4 (0 to -), and not ever class 7 (0 to +)?

**Comment by stefpeschel** [comment]
Hey Anton, 

The class assignment should be as you describe: If the association is close to zero in group A and negative in group B, it should be assigned to class 4. It could also fall into class 0 if the association in class B is negative but close to zero. 

Could you please provide me with a working example so I can take a look at this issue?

I've tested the function with the datasets used in my GitHub tutorials and found no inconsistencies. 

Best,
Stefanie

**Comment by antonkratz** [comment]
> Could you please provide me with a working example so I can take a look at this issue?

Hi Stephanie, I am unable to share the underlying data. However here is the code as minimal as I could make it:

```R
library("NetCoMi")

# Rows: OTUs. Columns: Samples.
df_stateA <- read.table("stateA.tsv", header = T)
df_stateB <- read.table("stateB.tsv", header = T)

# I need to transpose rows with columns for netConstruct
stateA <- t(df_stateA)
stateB <- t(df_stateB)

# Filter the 58 samples (sample size of the smaller group) with highest
# frequency to make the sample sizes equal and thus ensure comparability. 
n_yes = 58

# SPRING
duo_net <- netConstruct(data = stateA,
	data2 = stateB,
	filtTax = "highestFreq",
	filtTaxPar = list(highestFreq = n_yes),
	filtSamp = "totalReads",
	filtSampPar = list(totalReads = 1000),
	measure = "spring",
	measurePar = list(nlambda=10, rep.num=10),
	normMethod = "mclr", 
	zeroMethod = "none",
	sparsMethod = "none", 
	dissFunc = "signed",
	verbose = 2,
	seed = 123456)

duo_diff <- diffnet(duo_net,
                       diffMethod = "discordant",
		       discordThresh = .9, 
                       adjust = "lfdr")
```

**Comment by antonkratz** [comment]
P.S.: I will also try to make synthetic data to reproduce the error that I am definitely observing but that can take a a while as it unclear to me right now how to go about constructing such a data set.

**Comment by antonkratz** [comment]
> Hey Anton,
> 
> I tested the function with a dataset I have at hand and the class assignments are indeed wrong.
> 
> Since I couldn't find any inconsistencies in my code, I tried the examples in the discordant package and the same problem occurs there. So, I'll write an email to the package owners.
> 
> There were already some problems with the discordant package when I first used it. So, I only used the `discordantRun` function and replaced the other functions with my own corrected versions. However, the class assignments were correct at that time.
> 
> I saw that the latest discordant version was uploaded a few days ago, but updating the package didn't change anything. So, let's see what the authors say...

Thank you very much for looking into this! I am happy you see this error too. Yes, looking forward to input from the DISCORDANT team. I think it is worthwhile to fix this!
