### ISSUE TITLE
Sequences on the network plot instead of taxa

### ISSUE THREAD

**Issue by MicrobEva** [stefpeschel/NetCoMi#88]
Hello,
I am currently trying to build a microbiome network with my data from a phyloseq object, I have an issue with the labelScale option. Indeed, when labelScale = FALSE as suggested in the pipeline, sequences are appearing on the plot instead of their taxonomic assignment.
I suggest that it comes from labelScale because when I select it as TRUE, the sequences are not plotted anymore, but it could definitely comes from somewhere else.
Is there a way to fix it please? And thus, which one?

**Comment by stefpeschel** [comment]
Hey, 

When `labelScale` is set to TRUE, the labels are scaled based on the node size, which usually works well. Would you please send me the code you used for creating the plot so I can try to reproduce your issue?

Do you finally want to use the sequence/ASV names or the taxonomic assignments as node labels?

**Comment by MicrobEva** [comment]
Hey,
Thanks for your answer, I finally found that my problem was from my data. So I fixed it and it is working well now!

**Comment by stefpeschel** [comment]
Okay great. Glad to hear it's working now!
