### ISSUE TITLE
Change node shape according to taxonomy

### ISSUE THREAD

**Issue by nicolereynolds2** [stefpeschel/NetCoMi#92]
Hello,

Thanks for the package, it has been great!

I would like to change the node shapes in my network according to phylum, but I have not been able to figure out how to extract the taxonomy from the phyloseq object as a vector.

If you have any suggestions, I would appreciate it, thanks.

**Comment by stefpeschel** [comment]
Hey,
The taxonomy table can be accessed with `phyloseq::tax_table()`. From this matrix, you can select a column vector at the desired taxonomic level. Make sure you have agglomerated the data to the desired level in advance (see `phyloseq::taxglom()`).
Best,
Stefanie
