### ISSUE TITLE
nodeshape according to sample type

### ISSUE THREAD

**Issue by chrissy005** [stefpeschel/NetCoMi#94]
Dear @stefpeschel ,

Thank you for this amazing package which makes its so easy to get network plots.

I was wondering if it is possible to color nodes based on taxonomic ranks and also assign nodeshapes according to sample type in the same plot as seen in https://joey711.github.io/phyloseq/plot_network-examples.html?

**Comment by stefpeschel** [comment]
Please have a look at the section ["Network on genus level"](https://github.com/stefpeschel/NetCoMi#network-on-genus-level) in the readme. It explains how to color nodes according to their taxonomic rank. The plot function has an additional argument `featVecShape` which can be used equivalently to highlight features by different shapes. This must be a named vector that assigns a feature (sample type in your case) to each OTU/ASV/node.
