### ISSUE TITLE
Association matrices when comparing networks

### ISSUE THREAD

**Issue by gastronaut82** [stefpeschel/NetCoMi#96]
Hi there,

When comparing networks, you post a methodology that uses a stored permutation association matrices. 
In the code below - is assoPerm a matrix that is specific to the amgut data? Or is this something that can be used with other datasets?

amgut_comp4 <- netCompare(amgut_props, adjust = "BH",
                          permTest = TRUE, nPerm = 100L, 
                          fileLoadAssoPerm = "assoPerm",
                          seed = 123456)

Is this something you create first using:

createAssoPerm(amgut_props, nPerm = 100, 
               computeAsso = TRUE,
               fileStoreAssoPerm = "assoPerm",
               storeCountsPerm = TRUE, 
               fileStoreCountsPerm = c("countsPerm1", "countsPerm2"),
               append = FALSE, seed = 123456)

**Comment by stefpeschel** [comment]
Hi,

The `assoPerm` object must be created first to be reused in the same function or in other NetCoMi functions. It contains a list with the computed association/correlation matrices for each single permutation. In the tutorial, it contains the association matrices for the amgut data. Thus, they are data specific and cannot be used for other datasets. 

There are several functions that take the two arguments `storeAssoPerm` and `fileStoreAssoPerm`, such as netCompare, diffNet, and createAssoPerm. If you set `storeAssoPerm` to TRUE, the association matrices are stored in a file on your hard disk and can be reused later to save runtime. Please refer to the help pages for more information on the use of this argument.
